// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEqreOrKKxqJ7D0opc4tTSD5_Q3IePS8',
    appId: '1:1064156484537:web:65a9bd6c803a80214edc68',
    messagingSenderId: '1064156484537',
    projectId: 'focusmate-76371',
    authDomain: 'focusmate-76371.firebaseapp.com',
    storageBucket: 'focusmate-76371.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1k_3mn8qD8Ct-PGiyHyMtT6uz80_QJvM',
    appId: '1:1064156484537:android:096a72ec78b948044edc68',
    messagingSenderId: '1064156484537',
    projectId: 'focusmate-76371',
    storageBucket: 'focusmate-76371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlcGjnsHWJd76iuB4lBZ35jQXtxZbMxI',
    appId: '1:1064156484537:ios:b0d9ad8bb2b4f1404edc68',
    messagingSenderId: '1064156484537',
    projectId: 'focusmate-76371',
    storageBucket: 'focusmate-76371.firebasestorage.app',
    iosBundleId: 'com.example.focusmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQlcGjnsHWJd76iuB4lBZ35jQXtxZbMxI',
    appId: '1:1064156484537:ios:b0d9ad8bb2b4f1404edc68',
    messagingSenderId: '1064156484537',
    projectId: 'focusmate-76371',
    storageBucket: 'focusmate-76371.firebasestorage.app',
    iosBundleId: 'com.example.focusmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPEqreOrKKxqJ7D0opc4tTSD5_Q3IePS8',
    appId: '1:1064156484537:web:32ca15ff68a309e74edc68',
    messagingSenderId: '1064156484537',
    projectId: 'focusmate-76371',
    authDomain: 'focusmate-76371.firebaseapp.com',
    storageBucket: 'focusmate-76371.firebasestorage.app',
  );
}
